#!/bin/bash
#
# Sets screen brightness as a percentage of the maximum
# To be used with wrapper scripts which control incrementation
# DO NOT REMOVE LOWER LIMIT SAFEGUARD
# The screen cannot be turned back on for some reason


# Setup/Param Calcs:
handler="/sys/class/backlight/intel_backlight/"
max_br=$(cat $handler"max_brightness")
old_br=$(cat $handler"brightness")
old_br_p=$(( $old_br * 100 / $max_br ))

# Value Printing/Help Dialogue (no args):
if [ $# -ne 1 ]; then
    printf "\t------\ncurrent percent : %d\n" $old_br_p
    printf "USAGE:\n\tThis Help Dialogue         : setbright\n"
    printf "\tSet Percent Value Directly : setbright [integer]\n"
    printf "\tIncrease From Current      : setbright [+\-][integer]\n"

# Setting Brightness:
else
    setregex=^[0-9]+$      # integer regex
    relregex=^[+-][0-9]+$  # relative percent (+/-)amt
    new_br_p=50  # default value, values range from 1-10

    # Determining setting method
    if [[ $1 =~ $setregex ]]; then
        new_br_p=$1
    elif [[ $1 =~ $relregex ]]; then
        new_br_p=$(( $old_br_p $1 ))
    fi

    # Setting/bounds checking
    new_br=$(( $new_br_p * max_br / 100 ))
    # ideal range
    sudo chmod +666 $handler"brightness"
    if [ $new_br -le $max_br ] && [ $new_br -ge 44 ]; then
        echo $new_br > $handler"brightness"
    # overreach
    elif [ $new_br -gt $max_br ]; then
        echo $max_br > $handler"brightness"
    # underreach
    elif [ $new_br -lt 44 ]; then
        echo 44 > $handler"brightness"
    fi
fi
