#!/bin/bash
#
# Sets screen brightness by number value rather than a percent
# To be used with wrapper scripts which control incrementation
# DO NOT REMOVE LOWER LIMIT SAFEGUARD
# The screen cannot be turned back on for some reason


# Setup/Param Calcs:
handler="/sys/class/backlight/acpi_video0/"
max_br=$(cat $handler"max_brightness")
old_br=$(cat $handler"brightness")

# Value Printing/Help Dialogue:
if [ $# -ne 1 ]
then
    printf "\t------\ncurrent value   : %d\n" $old_br
    printf "USAGE:\n\tThis Help Dialogue         : setbright\n"
    printf "\tSet Percent Value Directly : setbright [integer]\n"
    printf "\tIncrease From Current      : setbright [+\-][integer]\n"

# Setting Brightness:
else
    setregex=^[0-9]+$      # integer regex
    relregex=^[+-][0-9]+$  # relative percent (+/-)amt
    new_br=5  # default value, values range from 1-10

    # Determining setting method
    if [[ $1 =~ $setregex ]]
    then
        new_br=$1
    else
        if [[ $1 =~ $relregex ]]
        then
            new_br=$(( $old_br_p $1 ))
        fi
    fi

    # Setting/bounds checking
    # ideal range
    sudo chmod +666 $handler"brightness"
    if [ $new_br -lt $max_br ] && [ $new_br -gt 0 ]
    then
        echo $new_br > $handler"brightness"
    fi
    # overreach
    if [ $new_br -gt $max_br ]
    then
        echo $max_br > $handler"brightness"
    fi
    # underreach
    if [ $new_br -lt 1 ]
    then
        echo 1 > $handler"brightness"
    fi
fi
