#!/bin/bash
#
# Controls screen brightness settings
# Idea from stack overflow/most online scree resources
# but customized and set up to my liking


# Setup/Param Calcs:
handler="/sys/class/backlight/intel_backlight/"
max_br=$(cat $handler"max_brightness")
old_br=$(cat $handler"brightness")
old_br_p=$(( $old_br * 100 / $max_br ))

# Value Printing/Help Dialogue:
if [ $# -ne 1 ]
then
    printf "\t------\ncurrent value   : %d\n" $old_br
    printf "current percent : %d\n" $old_br_p
    printf "USAGE:\n\tThis Help Dialogue         : setbright\n"
    printf "\tSet Percent Value Directly : setbright [integer]\n"
    printf "\tIncrease From Current      : setbright [+\-][integer]\n"

# Setting Brightness:
else
    setregex=^[0-9]+$      # integer regex
    relregex=^[+-][0-9]+$  # relative percent (+/-)amt
    new_br_p=50

    # Determining setting method
    if [[ $1 =~ $setregex ]]
    then
        new_br_p=$1
    else
        if [[ $1 =~ $relregex ]]
        then
            new_br_p=$(( $old_br_p $1 ))
        fi
    fi


    # Setting/bounds checking
    new_br=$(( $new_br_p * $max_br / 100 ))
    # ideal range
    if [ $new_br -lt $max_br ] && [ $new_br -gt 2 ]
    then
        echo $new_br > $handler"brightness"
    fi
    # overreach
    if [ $new_br -gt $max_br ]
    then
        echo $max_br > $handler"brightness"
    fi
    # underreach
    if [ $new_br -lt 2 ]
    then
        echo 2 > $handler"brightness"
    fi
fi
